Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -34,10 +34,10 @@ jobs:
     needs: build
     if: success()
     steps:
-      - name: List files
+      - name: List files before deployment
         run: ls -R
       
-      - name: Deploy Dockerfile to EC2
+      - name: Deploy files to EC2
         uses: appleboy/scp-action@v0.1.6
         with:
           host: ${{ secrets.EC2_HOST }}
@@ -47,6 +47,15 @@ jobs:
           target: "/home/${{ secrets.EC2_USER }}/"  # Use user directory
           debug: true  # Enable debug for more info
       
+      - name: List files on EC2
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.EC2_KEY }}
+          script: |
+            ls -R /home/${{ secrets.EC2_USER }}/  # Check files on EC2
+
       - name: SSH commands to deploy
         uses: appleboy/ssh-action@master
         with:
@@ -55,5 +64,12 @@ jobs:
           key: ${{ secrets.EC2_KEY }}
           script: |
             cd /home/${{ secrets.EC2_USER }}/  # Change to the correct directory
-            docker build -t sharing-titanic .
-            docker run -d -p 5000:5000 -p 3000:3000 sharing-titanic
+            if [ -f Dockerfile ]; then
+              echo "Dockerfile found. Building the image..."
+              docker build -t sharing-titanic .
+              echo "Running the Docker container..."
+              docker run -d -p 5000:5000 -p 3000:3000 sharing-titanic
+            else
+              echo "Dockerfile not found! Exiting..."
+              exit 1
+            fi
